# Generated by Django 3.1.7 on 2021-04-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_estado', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'uf',
            },
        ),
    ]
