# Generated by Django 3.1.7 on 2021-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=19)),
                ('codigo', models.IntegerField(max_length=5)),
                ('nome', models.CharField(max_length=60)),
                ('nome_fantasia', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('site', models.CharField(blank=True, max_length=70, null=True)),
                ('gerente_responsavel', models.CharField(blank=True, max_length=70, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=7)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=2)),
                ('observacao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seguradora',
            },
        ),
    ]
