# Generated by Django 3.1.7 on 2021-04-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguradora', '0002_auto_20210408_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'insurance',
            },
        ),
        migrations.RemoveField(
            model_name='seguradora',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='seguradora',
            name='nome_fantasia',
        ),
        migrations.RemoveField(
            model_name='seguradora',
            name='observacao',
        ),
        migrations.AddField(
            model_name='seguradora',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
