# Generated by Django 3.1.5 on 2021-04-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualificacao', '0001_initial'),
        ('uf', '0001_initial'),
        ('seguradora', '0002_auto_20210408_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=19)),
                ('nome', models.CharField(max_length=60)),
                ('nome_fantasia', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
                ('data_nascimento', models.DateField()),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('cnh_nro', models.CharField(blank=True, max_length=11, null=True)),
                ('cnh_data_validade', models.DateTimeField()),
                ('cnh_categoria', models.CharField(blank=True, max_length=2, null=True)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=7)),
                ('complemento', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=25)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('estado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uf.uf')),
                ('qualificacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qualificacao.qualificacao')),
                ('seguradora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguradora.seguradora')),
            ],
            options={
                'db_table': 'Pessoa',
            },
        ),
    ]
