# Generated by Django 3.1.7 on 2021-04-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20210408_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='seguradora',
        ),
    ]
