# Generated by Django 3.1.7 on 2021-04-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_remove_pessoa_seguradora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nome_fantasia',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cnh_data_validade',
            field=models.DateField(),
        ),
    ]
