# Generated by Django 3.1.7 on 2021-04-25 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20210424_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cnh_data_validade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
    ]
